# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Sutdown"

[social.params]
icon = "brand-github"

[[social]]
identifier = "Zhihu"
name = "Zhihu"
url = "https://www.zhihu.com/people/mcgyfw"

[social.params]
icon = "brand-twitter"
